// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoEMap.Classes;

namespace PoEMap.Migrations
{
    [DbContext(typeof(StashContext))]
    [Migration("20190122141548_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("PoEMap.Classes.Map", b =>
                {
                    b.Property<string>("MapId");

                    b.Property<string>("IconAddress");

                    b.Property<string>("League");

                    b.Property<string>("MapName");

                    b.Property<string>("Note");

                    b.Property<string>("Price");

                    b.Property<string>("StashId");

                    b.HasKey("MapId");

                    b.HasIndex("StashId");

                    b.ToTable("MapsDb");
                });

            modelBuilder.Entity("PoEMap.Classes.Stash", b =>
                {
                    b.Property<string>("StashId");

                    b.Property<string>("Seller");

                    b.Property<string>("StashName");

                    b.HasKey("StashId");

                    b.ToTable("StashesDb");
                });

            modelBuilder.Entity("PoEMap.Classes.Map", b =>
                {
                    b.HasOne("PoEMap.Classes.Stash", "Stash")
                        .WithMany("Maps")
                        .HasForeignKey("StashId");
                });
#pragma warning restore 612, 618
        }
    }
}
