// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PoEMap.Classes;
using System;

namespace PoEMap.Migrations
{
    [DbContext(typeof(StashContext))]
    [Migration("20190117163245_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PoEMap.Classes.Stash", b =>
                {
                    b.Property<string>("StashId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Seller");

                    b.Property<string>("StashName");

                    b.HasKey("StashId");

                    b.ToTable("StashesDb");
                });
#pragma warning restore 612, 618
        }
    }
}
